name: BetterChatFilter
version: '1.1.2'

main: dev.gomez.java.betterChatFilter.BetterChatFilter
api-version: '1.21'
load: POSTWORLD
commands:
  bcf:
    description: "Reload BetterChatFilter config"
    usage: "/bcf reload"
    permission: betterchatfilter.reload
    permission-message: "You do not have permission to use this command"

permissions:
  betterchatfilter.reload:
    description: "This gives access to /bcf reload"
    default: op
  betterchatfilter.notify.update:
    description: "This gives an plugin update notification"
    default: op